### ISSUE TITLE
Add mode for smaller terminal widths

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/pastel#11]
Basically like a "reactive" web page: choose a smaller output width if the terminal width is too small to display the full canvas width.

**Comment by pickfire** [comment]
I think this is already working good with terminal width < 80. Except some parts where the height may exceed 24 characters.

**Comment by sharkdp** [comment]
Agreed. Given that this would make the code quite a bit more complicated, let's close this for now. Concerning the height, see #72 which would improve the situation with vertical real estate.
