### ISSUE TITLE
Colourcheck fails in tmux

### ISSUE THREAD

**Issue by daphniz** [sharkdp/pastel#110]
For me, the result of `pastel colorcheck` is as expected in xterm, but not in xterm/tmux, where the lower squares are different shades of grey.

**Comment by sharkdp** [comment]
Same for me. I guess tmux does not support 24-bit colors?

**Comment by daphniz** [comment]
It does.  I got it to work by adding

	set -ga terminal-overrides ",xterm-256color:Tc"
	
to `.tmux.conf`.

**Comment by sharkdp** [comment]
So this is actually an example of `pastel colorcheck` working correctly :smile: - thank you for the feedback!
