### ISSUE TITLE
Mix working incorrectly, with some colours...

### ISSUE THREAD

**Issue by johnalanwoods** [sharkdp/pastel#112]
I am using the command 

`pastel mix yellow blue` on the latest build `pastel 0.6.1`, and I get the following:

As you can see, red and yellow make orange, but yellow and blue make purple? - should be green no?

<img width="358" alt="Screenshot 2020-01-28 at 10 39 48 a m" src="https://user-images.githubusercontent.com/5158898/73256811-8a67c380-41ba-11ea-9e2d-9e1399d2bf7b.png">

**Comment by sharkdp** [comment]
That depends on the colorspace which is used to mix the colors. If you use the HSL space, the result is green:
```
pastel mix blue yellow -s HSL
```

**Comment by johnalanwoods** [comment]
@sharkdp - oh sorry! I don't understand why it's not green in RGB, but clearly not a bug!

Thanks! cool app By the way.
