### ISSUE TITLE
Feature: make `pastel gradient` accept more than two colors

### ISSUE THREAD

**Issue by bbkane** [sharkdp/pastel#117]
## Feature

It'd be fun for me if `pastel gradient` would accept more than two colors and generate the gradient between them.

For example, I can generate a gradient between white, green, and red with the following:

```
cat <(pastel gradient white green) <(pastel gradient green red | sed 1d)
```

I'd like to generate it with:

```
pastel gradient white green red
```

## Use Case

I'm using `pastel` for my shell prompt ( https://github.com/bbkane/dotfiles/tree/master/zsh#install-prompt ) and this would make it even more ~distracting~ interesting.

## Potential Problems

Not sure the best way to deal with weird `-n` options:

```
pastel gradient -n 2 white green red   # what does this do? Throw an error?
```

Thanks for pastel!

**Comment by sharkdp** [comment]
This is supported in the latest version: https://github.com/sharkdp/pastel/releases/tag/v0.7.0

**Comment by bbkane** [comment]
Oh great, thank you!
