### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by muv1** [sharkdp/pastel#119]
It seems Windows build it not currently available.

It that intentional or an oversight?

Thank you!

**Comment by sharkdp** [comment]
> It that intentional or an oversight?

Neither. Deployment of Windows binaries hasn't been worked on by anyone, so far.

**Comment by muv1** [comment]
Looks pretty straightforward, as no C crates that I saw (thanks for that by the way). I built with this:

~~~sh
RUSTFLAGS='-C link-arg=-s' cargo install pastel
~~~

Not sure the right way to go about this, but heres the result:

[pastel.zip](https://github.com/sharkdp/pastel/files/4309209/pastel.zip)

**Comment by sharkdp** [comment]
Yes, we invested a bit of effort to get `pastel` running on Windows and we also have CI set up to make sure it doesn't break (https://github.com/sharkdp/pastel/blob/85266df0f8780619ed3470efab101e16e20dbf3c/.travis.yml#L32-L34).

I will not find the time to manually upload Windows binaries for all releases of my projects, so if someone interested in having binaries for Windows, we need to automate this (like we do for other platforms as well)

**Comment by muv1** [comment]
Before that happens, seem some other issue need to be addressed. Running something like `pastel color hotpink`, just produces black and white output. This is with `cmd.exe` and also `mintty.exe`, havent tried other terminals.

**Comment by sharkdp** [comment]
please see if this thread can help: #45 

- you might need to set `COLORTERM=truecolor`
- or try `pastel`s `-f`/`--force-color` option

**Comment by muv1** [comment]
These both work with Mintty:

~~~
pastel -f color hotpink
pastel --color-mode=8bit color hotpink
~~~

nothing works with `cmd.exe`, I think that would be difficult as it doesnt support ANSI codes, so would need to use Windows API. I think one of these takes care of that though:

- https://github.com/BurntSushi/termcolor
- https://github.com/mackwic/colored

**Comment by lzybkr** [comment]
@muv1 - Are you running on Windows 10? It supports ANSI:

![image](https://user-images.githubusercontent.com/2148248/76269039-64a7f280-622d-11ea-95aa-3651f77dc391.png)

**Comment by muv1** [comment]
@lzybkr yeah sorry I meant pre Windows 10 `cmd.exe`.

**Comment by lzybkr** [comment]
@muv1 - I don't think it's necessary to add support for non-ANSI capable terminals because:
* Win7 is out of support - most should be on Win10 already
* Pastel isn't much less useful if the terminal only supports 16 colors.

**Comment by muv1** [comment]
@lzybkr good point, so I guess all that need to be done is decide if automated Windows builds is something that should be supported

**Comment by rivy** [comment]
I just created a PR that adds a GitHub Actions CICD workflow (see PR #120).

It automatically builds and tests all platforms (including windows), retaining the build products as artifacts for later use. It will also automatically deploy everything to a GitHub release when the commit is version tagged (ie, tag matching /[vV]?[0-9].*/).

All tests are passing and all builds are being packaged.

* CI tests: <https://github.com/rivy/rs.pastel/actions/runs/53247767>
* builds: <https://github.com/rivy/rs.pastel/releases/tag/v0.7.0.2>
