### ISSUE TITLE
pastel pick doesn't display all colors

### ISSUE THREAD

**Issue by nycex** [sharkdp/pastel#121]
When I run `pastel pick` in st or urxvt, i get a output like ![output_image](https://user-images.githubusercontent.com/24685286/78463921-30680a80-76e3-11ea-8936-a3c700bb5f0f.png)
even though when running this:
```sh
awk 'BEGIN{
    s="/\\/\\/\\/\\/\\"; s=s s s s s s s s;
    for (colnum = 0; colnum<77; colnum++) {
        r = 255-(colnum*255/76);
        g = (colnum*510/76);
        b = (colnum*255/76);
        if (g>255) g = 510-g;
        printf "\033[48;2;%d;%d;%dm", r,g,b;
        printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
        printf "%s\033[0m", substr(s,colnum+1,1);
    }
    printf "\n";
}'
```
from https://gist.github.com/XVilka/8346728, I get a smooth gradient:
![gradient_image](https://user-images.githubusercontent.com/24685286/78463968-dca9f100-76e3-11ea-9de0-c91350367a23.png)
In alacritty, it seems to work though:
![alacritty_output_image](https://user-images.githubusercontent.com/24685286/78463977-04995480-76e4-11ea-8422-e01ad938f32d.png)

**Comment by sharkdp** [comment]
It appears that `urxvt` does not set the `COLORTERM` variable to `truecolor`, which is the only way how we can detect that a terminal emulator supports 24bit colors.

If you run `pastel colorcheck`, you should be able to clearly determine whether or 24bit is supported.

**Comment by sharkdp** [comment]
Don't you see a warning in the top output of `pastel pick`?

![image](https://user-images.githubusercontent.com/4209276/78473586-17427680-7742-11ea-8cae-6f7724bc391d.png)

**Comment by nycex** [comment]
Well, I saw the warning and set the environment variable `PASTEL_COLOR_MODE=24bit`. With this enabled, I get the output in st and urxvt, i showed earlier. But now that I tried, when I set `COLORTERM=24bit` or `COLORTERM=truecolor`, then it shows correctly all the colors like in alacritty. Maybe there is a problem with the check for PASTEL_COLOR_ODE

**Comment by sharkdp** [comment]
> Maybe there is a problem with the check for `PASTEL_COLOR_MODE`

It looks like there is, yes. I can reproduce it. Thank you for reporting this!

**Comment by yugonline** [comment]
Can you explain where to start? I can give this a go but I'm new to Rust. So I'll timebox it to not waste time.

**Comment by sharkdp** [comment]
@yugonline Sorry for the delay. Are you still interested in tackling this?

**Comment by sharkdp** [comment]
So to reproduce this, run:
```
COLORTERM="" PASTEL_COLOR_MODE=24bit pastel pick
```

It should show a smooth color palette (like for `COLORTERM="truecolor" pastel pick`), and not with a restricted color depth, like in the screenshot above.


Next, look into `src/cli/colorpicker.rs` and start here:
```
    let mut canvas = Canvas::new(
        width + 2 * config.padding,
        width + 2 * config.padding,
        Brush::from_environment(Stream::Stderr),
    );
```

The problem is the `Brush::from_environment(Stream::Stderr)` call which detects colordepth support by checking whether STDERR is an interactive terminal or not. Instead, it should also take into account environment variables. Search for `COLORTERM` and `PASTEL_COLOR_MODE`, to see how it is used in other places.

**Comment by yugonline** [comment]
Sounds good I'll take a look!
