### ISSUE TITLE
Add support for RGBA?

### ISSUE THREAD

**Issue by drager** [sharkdp/pastel#131]
Hello!

Would be cool if support could be added for `rgba()`. E.g: `pastel "rgba(0, 0, 0, 0.1)"`. Could perhaps output something like this:
```
Name: black                    
Hex: #000000  
RGB: rgb(0, 0, 0)              
RGBA: rgba(0, 0, 0, 0.1)            
HSL: hsl(0, 0.0%, 0.0%)        
Opacity: 0.1
```

Backstory is that I find myself copying colors from design tools which can give my something rgba values in my clipboard. Would be nice to use directly with pastel without changing the output from the clipboard.

**Comment by sharkdp** [comment]
Thank you for the feature request.

Sounds like a good idea, but I guess that would be quite some work. 

It would be nice to display alpha != 1 colors with the checkerboard pattern slightly "shining through". This could be achieved using appropriate mixing/blending with the checkerboard colors.
