### ISSUE TITLE
pastel on NetBSD

### ISSUE THREAD

**Issue by voidpin** [sharkdp/pastel#132]
FYI, I've packaged `pastel` and pushed it to the NetBSD repo, https://pkgsrc.se/graphics/pastel

**Comment by sharkdp** [comment]
Thank you very much! Should we put some instructions in the README here: https://github.com/sharkdp/pastel#installation ?

**Comment by voidpin** [comment]
If you want to. To install on NetBSD,
1) using the package manager
`# pkgin install pastel`

2) building from source
```
$ cd /usr/pkgsrc/graphics/pastel
# make install
```

**Comment by sharkdp** [comment]
Done, thanks!
