### ISSUE TITLE
OPINION: Divide the lib and cli tool into two repositories ???

### ISSUE THREAD

**Issue by bresilla** [sharkdp/pastel#135]
I was thinking why not divide the pastel and its color lib. I actually wanted to do that, to create a repo, but since it is your code, i thought maybe agree and you can divide, and if not, then i already created a repo and named it 'blush' - an thesaurus alternative for 'color' (cos all other names - color, colors, colorspace, brush, paint, dye ... are already crates). There are many reasons why: like lot of issues are cli related (thus better issue management). Then not many crates have all those colors like pastel supports. Another one is that a lot of other tools could use t instead of creating its own color structs (example xcolor) or so it could be good for people that use WASM and have nothing to do with cli.

Anyway. There is a lot of functionalities a would like to the library like: clustering (i have created some functions based on machine-learning), then chromatic scales to generate sequential color-schemes (ratinal, linear and so on) check: https://ai.googleblog.com/2019/08/turbo-improved-rainbow-colormap-for.html...

If you think it's a good idea, then i could help with it. So the "pastel" could be the name of the tool, cos i think most of the people use that and relate to, and then use another crate name (like "blush" or anything you want) for the color library...

**Comment by pgimalac** [comment]
Hello, I'm curious as to why this has been closed, I'd say it's a good idea which would allow to use all the interesting functions without getting clap as a bonus dependency.

It might also help making this crate more of a color library than just a binary.

What do you think @sharkdp ?

**Comment by sharkdp** [comment]
Probably a good idea, but I'm currently not willing to invest the effort.

**Comment by pgimalac** [comment]
Haha that's fair
