### ISSUE TITLE
github release v0.8.1

### ISSUE THREAD

**Issue by Artturin** [sharkdp/pastel#144]
you forgot to create a gh release for v0.8.1

**Comment by sharkdp** [comment]
Thanks, but I didn't forget it. I wanted to include more stuff before I create the release (#143 and maybe #140). I just prepared for the release by bumping the version in `Cargo.toml`.

I know there is a build error currently with the latest Rust version, so maybe let's just create the release and push another one when these PRs are ready.

**Comment by sharkdp** [comment]
See https://github.com/sharkdp/pastel/releases/tag/v0.8.1
