### ISSUE TITLE
Most similar colors option

### ISSUE THREAD

**Issue by BelkaDev** [sharkdp/pastel#145]
Hi, 
there don't seem to be an option to get the most similar colors as an option, something like `pastel similar <color>` but it shows in the color info
![image](https://user-images.githubusercontent.com/49416514/128843941-f61c5396-d239-4c1a-a984-7f4f4d6f9c9a.png)
`pastel color red | grep tomato` doesn't work either
How can I fetch these values?

**Comment by sharkdp** [comment]
Hm, if you want all of these names - that's not possible at the moment. What you can do is to use `pastel format name <color>` which will look up a close-by color name. This is equivalent to the first entry in the list... unless you start with something like `red`/`#ff0000` - where it will (obviously) show "red", not "orangered".
