### ISSUE TITLE
fzf preview window does not show colors from pastel's output

### ISSUE THREAD

**Issue by reportaman** [sharkdp/pastel#146]
https://github.com/junegunn/fzf's ``fzf --preview``, even with ``--ansi`` option does not color lines returned by pastel.

The reason to have this fixed is: fzf with preview window is very powerful, and can enable users to preview color schemes in its preview window. Combined with pastel, it can become a color scheme previewer & search method of choice for many projects.

Here's an example, and minimal demo commands:

On stdout, pastel output retains color:
![Screen Shot 2021-08-13 at 8 44 08 PM](https://user-images.githubusercontent.com/71736629/129433117-a4dd6d12-5e9b-4de4-af4f-0b4487b338c0.png)
In fzf preview window it does not:
![Screen Shot 2021-08-13 at 8 44 36 PM](https://user-images.githubusercontent.com/71736629/129433118-c9ccfd0f-ee12-4317-aba4-e24864f259ec.png)

Try these example commands:

1) Doesn't work:
```
fzf --ansi --preview 'pastel paint "#ff0000" --on "#0000ff" "Hello world"'
```

2) Works:
```
fzf --ansi --preview 'echo "\033[41mHello world\033[0m"'
```

**Comment by sharkdp** [comment]
You need to use pastels `--force-color` mode. Let me know if that works for you.

**Comment by reportaman** [comment]
@sharkdp Thanks a lot! It worked!

```
fzf --ansi --preview 'pastel -f paint "#ff0000" --on "#0000ff" "Hello world"'
```

**Comment by sharkdp** [comment]
I'd be interested to see what you are doing with that exactly :-)

**Comment by reportaman** [comment]
@sharkdp I am coding a [tmux](https://github.com/tmux/tmux) colorscheme picker using [fzf](https://github.com/junegunn/fzf), pastel, and [Gogh color schemes]( https://github.com/Mayccoll/Gogh). Gogh repository provides colorschemes in json format, its list is fed to fzf for user to navigate and select one, and colors are fed to pastel to print a sample of selected colorscheme in fzf's preview window. This way one can preview, and even change the colorscheme without having to edit any files or having to close tmux.

**Comment by sharkdp** [comment]
Cool!
