### ISSUE TITLE
Colorpicker options

### ISSUE THREAD

**Issue by rashil2000** [sharkdp/pastel#150]
I see that there are no colorpicker options for Windows as of now.

There are 2 popular choices (third party): 
- [Just Color Picker](https://annystudio.com/software/colorpicker) - both Windows and macOS
- [Free Color Picker](https://www.pazera-software.com/products/free-color-picker) (open source) - Windows

Both these can be invoked from the commandline (`jcpicker` and `freecolorpicker` respectively).

**Comment by rashil2000** [comment]
I discovered [wcolor](https://github.com/Elvyria/wcolor) yesterday, which is pretty simple to use and is inspired by xcolor (Linux). Would it be okay if make a PR for it?

**Comment by sharkdp** [comment]
Sure!
