### ISSUE TITLE
Can this Generate a Sequence of Color Shade strings?

### ISSUE THREAD

**Issue by ZionGates** [sharkdp/pastel#161]
Greeting. Lets say I have a base color and I need a list of 10 color shades (dark to light)
Can this tool generate a side by side string of darker to lighter colors for the specified color. 
I want output like the text immediately below.
**Like #ff6f00,#ff8f00,#ffa000,#ffb300,#ffc107,#ffca28,#ffd54f,#ffe082,#ffecb3,#fff8e1**

In other words I want to generate a color sequence (where I set the steps like 10,12, 8 etc.
![image](https://user-images.githubusercontent.com/1215869/160666745-682c9e2c-f404-4a04-9355-15e05093f94c.png)

![image](https://user-images.githubusercontent.com/1215869/160666452-d7e9ea4d-a7f8-4b7a-8cd6-8ba1d9135606.png)

**Comment by sharkdp** [comment]
Yes, this should be possible with `pastel gradient`. Let me know if this works for you.

![image](https://user-images.githubusercontent.com/4209276/160991861-0c7ee512-7642-4325-96f5-2b836585f101.png)

**Comment by ZionGates** [comment]
Worked perfect! Thanks.
Please introduce support for Alpha Transparency as well (#FF000000) for the gradient function at least.

**Comment by sharkdp** [comment]
please see https://github.com/sharkdp/pastel/issues/131
