### ISSUE TITLE
[pastel error]: Could not find any external color picker tool

### ISSUE THREAD

**Issue by potatoqualitee** [sharkdp/pastel#170]
Hello,
First, I love this tool! I use it extensively in my own OSS projects and I'm currently writing a PowerShell wrapper for it.

I'm having an issue with `pastel pick` on Windows, Linux and presumably mac. `Pipette`  is in my path and works when I call it from the command line but pastel keeps reporting

```
[pastel error]: Could not find any external color picker tool. See 'pastel pick -h' for more information.
```

`pastel pick -h` does not help. Please advise.

**Comment by potatoqualitee** [comment]
nm!

```
--color-picker <color-picker>
            Use a specific tool to pick the colors [possible values: gpick, xcolor, wcolor, grabc,
            colorpicker, chameleon, kcolorchooser, zenity, yad]
```

**Comment by sharkdp** [comment]
Exactly. You don't actually need to specify `--color-picker` usually. But you need to have one of these tools available in your PATH
