### ISSUE TITLE
Picking directly from terminal

### ISSUE THREAD

**Issue by Kabouik** [sharkdp/pastel#171]
The demo shows `pastel pick` working directly from the terminal, but somehow when I try it it inevitably opens `yad` and I don't see any options to disable that, the help even states that an external color picker is required. Is it something that changed in updates since the demo was recorded, and is there a way to force picking from terminal?

**Comment by sharkdp** [comment]
> The demo shows `pastel pick` working directly from the terminal

Not really, no. That's also a "GUI" picker with a very minimal interface (just a cursor). Maybe `grabc`. See `pastel pick --help` for a list of supported tools.

**Comment by Kabouik** [comment]
Oh right, I see now. `grabc` is not available for my distribution but I'll look into packaging it one day maybe. Thank you and sorry for the noise.
