### ISSUE TITLE
colorcheck not in commands list ?

### ISSUE THREAD

**Issue by simonmichael** [sharkdp/pastel#179]
Thanks for this wonderful tool!

The valuable `colorcheck` command seems not to be listed in the `pastel` subcommands list ?

**Comment by sharkdp** [comment]
Thank you for the feedback.

True, `colorcheck` is hidden by default because I thought of it as a debugging tool. Not a generally useful command. You seem to think otherwise?

**Comment by simonmichael** [comment]
Yes I think commands for debugging and learning about terminals' colour behaviour are very useful. It's the reason I found and used pastel.

**Comment by sharkdp** [comment]
Okay, let's change it then. It's a simple one-line change :-)
