### ISSUE TITLE
`pastel pick` does not work and suggests unhelpful advice.

### ISSUE THREAD

**Issue by vi** [sharkdp/pastel#180]
```
$ pastel pick
<large square with colour samples in terminal>
[pastel error]: Could not find any external color picker tool. See 'pastel pick -h' for more information.

$ pastel pick -h
pastel-pick
Interactively pick a color from the screen (pipette)

USAGE:
    pastel pick [count]

ARGS:
    <count>    Number of colors to pick [default: 1]

OPTIONS:
    -h, --help    Print help information
```

I expected to be information about external colour picker tools in `pastel pick -h` output, but there are no actionable items provided in the help output, only regular usage message.

**Comment by sharkdp** [comment]
Thank you for reporting that. I think it should say:

"See 'pastel -h' for more information: the `--color-picker` option lists possible tools."
