### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by jtmr05** [sharkdp/pastel#196]
The Arch Linux package should list the supported color pickers for pastel as optional dependencies, which isn't what's happening as of now.

**Comment by joveian** [comment]
It doesn't look like the developer of pastel is the maintainer of the Arch package so I don't think an issue here will help.  It looks like Arch package issues are disabled at the moment but you could email the maintainer listed at the top of [this file](https://gitlab.archlinux.org/archlinux/packaging/packages/pastel/-/blob/main/PKGBUILD?ref_type=heads).  Ideally with a diff (adding [optdepends](https://wiki.archlinux.org/title/PKGBUILD#optdepends)) or at least check and mention what supported pickers are available as Arch packages.

**Comment by jtmr05** [comment]
Thank you. I simply assumed there some cooperation/communication existed between the maintainers of this repo and the packager, but I guess that's not the case.
