### ISSUE TITLE
Add Lab format (to parser and output)

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/pastel#3]
- [x] input
- [x] output

**Comment by shawnohare** [comment]
Is CIELab format parseable now? I notice only the output task has been checked. I was excited to use this tool, but pastel could not parse the CIELab format as of a fresh install yesterday.

**Comment by sharkdp** [comment]
The reason I closed this ticket is that conversion from Lab (to RGB) can be confusing because you can easily reach the edge of RGB space (fully saturated colors), because the sRGB gamut has such a weird shape in Lab space.

In any case, that's not really a reason *not* to implement this. We should add this.

This should be really straightforward to implement, as we already have `Color::from_lab`. It just needs a simple Regex in `src/cli/parser.rs`.

**Comment by MusiKid** [comment]
Hi!
I tried to parse this format but there isn't a string to distinguish them (like HSL() or RGB()) so I just use the prefix `CEILab()`. Is it good?

**Comment by sharkdp** [comment]
@MusiKid Thank you for looking into this. I think it would be great if we could support both `CIELab(…)` (not `CEI`…) as well as `Lab(…)`, case insensitive.

Regex could be something like `(cie)?lab\(…`

**Comment by MusiKid** [comment]
Oh yes, sorry! It's effectively CIELAB. And I think that the regex should be more like `(?:cie)?lab\(` because we don't need to capture this group.

**Comment by sharkdp** [comment]
closed via #101 by @MusiKid
