### ISSUE TITLE
Add more named colors?

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/pastel#32]
Check other sources for more "named" colors:

* CamelCase variants of named colors? `SandyBrown`? https://www.youtube.com/watch?v=HmStJQzclHc
* consistently use both "gray" and "grey"
* Matplotlib color "names": `'b', 'g', 'r', 'c', 'm', 'y', 'k', 'w'`
* https://xkcd.com/color/rgb/
* https://github.com/tajmone/name-that-color#colors-names

**Comment by sharkdp** [comment]
Not for now...

**Comment by data-man** [comment]
I added all colors (956 colors :smile:) from Wikipedia's article [List_of_colors](https://en.wikipedia.org/wiki/List_of_colors:_A–F) in my branch [more_colors](https://github.com/data-man/pastel/tree/more_colors).
And commented deduplication in some places.
![Screenshot_20190902_020110](https://user-images.githubusercontent.com/1754269/64082265-c3902a80-cd25-11e9-9403-c83f91249090.png)

Some ideas:

- indroduce color groups: X11, CSS, Crayola, Pantone, etc.
- or even better: to allow the user to have own file with colors (TOML/CSV/JSON, etc.)

**Comment by sharkdp** [comment]
@data-man: Nice, thanks for trying it out.

I agree. If we are going to include this in `pastel`, we should provide multiple lists like you suggested. For now, I would like to avoid user-defined configuration files.

**Comment by data-man** [comment]
I added X11 colors from [oscolor.c](https://cgit.freedesktop.org/xorg/xserver/plain/os/oscolor.c). Now 1388 colors! :smile:

Other changes:
- colors outputs with full names (with spaces and other symbols as in Wiki's article)
- but the search is done by stripped and lowered names

Let me know if you want these changes.
