### ISSUE TITLE
Test on Windows

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/pastel#45]
- [x] do we have to include the code to enable ANSI codes on Windows? This does not seem to be required on Windows 10?
- [x] Make sure that we don't show the "COLORTERM" warning. PowerShell is not going to set this for us.
- [ ] `pastel pick` => any supported tools?

**Comment by sharkdp** [comment]
Due to the fix by @lzybkr, we now have working truecolor support on Windows.

However, the `output_vt100` crate only seems to enable truecolor support for STDOUT, not for STDERR:
https://github.com/Phundrak/output-vt100-rs/blob/795d3ecf77e8a6bfbd259dfb52c72231452b1b00/src/lib.rs#L30-L33

I guess this is the reason that the color spectrum in `pastel pick` does not show up in truecolor:
![image](https://user-images.githubusercontent.com/4209276/63654170-fdd25880-c776-11e9-9f50-73aa3b47cf05.png)

Apart from that, everything seems to work fine:
![image](https://user-images.githubusercontent.com/4209276/63654179-21959e80-c777-11e9-9816-565f4fbe117e.png)

**Comment by sharkdp** [comment]
`ansi_term` does the following:
https://github.com/ogham/rust-ansi-term/blob/451c1ab78f4e8c146512998ef7b5963fed04540f/src/windows.rs#L25-L27

See also https://github.com/ogham/rust-ansi-term/pull/50 for an explanation.

**Comment by sharkdp** [comment]
@rivy Thank you very much for the clarification! I was on the wrong way there..

Your comment actually made me look into our code again and it turns out that this was still a problem with `pastel`. There were actually two places where I checked for the `COLORTERM` environment variable and only one of them was "patched" in #68 to always yield "truecolor" for Windows.

I just pushed an update that fixes the issue:

![image](https://user-images.githubusercontent.com/4209276/63809054-a45a5d00-c921-11e9-9252-2a5fc07d8373.png)

**Comment by sharkdp** [comment]
Now we just need an external colorpicker for Windows that we could add here:
https://github.com/sharkdp/pastel/blob/4ba074cd38b278b3159aea2b36874840089a145d/src/cli/colorpicker.rs#L64-L97

**Comment by sharkdp** [comment]
Going to close this for now. If someone finds a colorpicker for Windows that could be included, let me know. Apart from this, the Windows build should work just fine.

**Comment by kvnxiao** [comment]
@sharkdp I know this issue is currently closed but would you be releasing pre-build Windows .exe binaries for this?

**Comment by sharkdp** [comment]
If someone wants to write the deployment scripts (via travis or appveyor), I'm happy to include them. But I'm probably not going to work on this on my own. (Deployment code for Windows can be found in my other Rust projects, e.g. `bat` or `fd`).

**Comment by muv1** [comment]
https://github.com/sharkdp/pastel/issues/119
