### ISSUE TITLE
Arch linux build error (no default toolchain configured)

### ISSUE THREAD

**Issue by A1rPun** [sharkdp/pastel#71]
I have trouble installing this awesome package on my distro using:
```
$ yay -S pastel
```

The following gets logged to console:
```
==> Starting build()...
error: no default toolchain configured
==> ERROR: A failure occurred in build().
    Aborting...
Error making: pastel
```

My `yay` version
```
$ yay --version
yay v9.2.0 - libalpm v11.0.3
```

I'm not sure if this is the right place for this error but it is definitely related.

**Comment by sharkdp** [comment]
Maybe @wezm can help?

**Comment by wezm** [comment]
@A1rPun sounds like you have installed `rustup` from the Arch repos but not installed a Rust toolchain. Try this, then try installing `pastel` again:

    rustup update stable

**Comment by A1rPun** [comment]
Great! I also had to run the following to make it install:
```
$ rustup default stable
```
