### ISSUE TITLE
Should have a more straight-forward name

### ISSUE THREAD

**Issue by mitnk** [sharkdp/pastel#82]
Like `colorl`, or `colorlist`, or `color`. `pastel` may be forgotten after 1 month not using it - "I remember I used a cool color cli tool and now I forgot its name".

> Searching google for "rust color cli" seems no "pastel" in first page. Maybe it will be after this issue is created :=)

**Comment by Hrxn** [comment]
Well, I think it is pretty straightforward, considering that pastel is a type of color.
Just ask a dictionary of your liking.

**Comment by sharkdp** [comment]
Thank you for your feedback.

I like the name :smile:. 

> Searching google for "rust color cli" seems no "pastel" in first page. Maybe it will be after this issue is created

This project was published a few days ago...

Having a too generic name would certainly not help with discoverability.

Another thing to keep in mind is if the name is already taken. `pastel` was still free in a lot of package repositories and on crates.io.
